name : TerraformInfra+DeploymentASP
on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-Latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: azure login
            uses: azure/login@v1
            with:
              cred: ${{secrets.AZURE_CREDENTIALS}}
          - name: Terraform setup
            uses: hashicorp/setup-terraform@v3
          - name: Terraform Init
            working-directory: Terraform
            run: terraform init
          - name: Terraform apply
            working-directory: Terraform
            run: terraform apply -auto-approve
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 10.0.x
          - name: Publish Artifacts
            run: dotnet publish Amazon.csproj -c Release -o publish
          - name: Deploy to azure webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: gitAmazon-5669
              package: publish

            
